spring:
  application:
    name: taskapi

  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true